# Generated by Django 3.2.10 on 2021-12-21 19:16
# pylint: skip-file

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("ip", models.CharField(max_length=255)),
                ("result", models.TextField()),
            ],
        ),
    ]
